### ISSUE TITLE
TextTests "ThirtyDays" Test Contains 31 Days

### ISSUE THREAD

**Issue by sheyll** [emilybache/GildedRose-Refactoring-Kata#10]
Hello,

It might by knit-picking but the number of days contained in `texttests/ThirtyDays/stdout.gr` is actually _31_ although the title suggests _30_ entries.

Regards,
Sven Heyll

**Comment by emilybache** [comment]
there are only two hard things... (http://martinfowler.com/bliki/TwoHardThings.html) in this case I don't think it's a very important off by one error. But well spotted!

**Comment by sheyll** [comment]
Thanks for linking to this hilarious joke/wisdom :)

**Comment by sheyll** [comment]
Still broken though ;P
