### ISSUE TITLE
Links at the bottom of the page don't work

### ISSUE THREAD

**Issue by tonidezman** [emilybache/GildedRose-Refactoring-Kata#108]
links like [Ruby](https://cyber-dojo.org/forker/fork/A8943EAF92?avatar=hippo&tag=9) gives us Rails routing error

**Comment by emilybache** [comment]
Thanks for pointing this out, I probably need to update these links.

**Comment by Neppord** [comment]
@tonidezman this seams fixed, do you still have the same issue?

**Comment by tonidezman** [comment]
Yes @Neppord this is fixed.

**Comment by tonidezman** [comment]
And Emily thanks for being awesome person and speaker.
