### ISSUE TITLE
Create `with_tests` branch

### ISSUE THREAD

**Issue by Pen-y-Fan** [emilybache/GildedRose-Refactoring-Kata#158]
I've noticed on the [Supermarket Receipt Refactoring Kata](https://github.com/emilybache/SupermarketReceipt-Refactoring-Kata) a `with_tests` branch has been optionally provided. I was thinking of creating the same for this Kata (PHP version), which, as that will allow jumping directly into the refactoring part of this exercise too.

I wanted to get your opinion, as this is the most stared Kata, and most versions, adding a new branch may create more work for you.

I was also going to update the PHP version to the same tooling and similar README as the others I've recently done, which would keep the install method and tooling consistent across Katas.

**Comment by emilybache** [comment]
The main branch has tests already, with the tool 'texttest'. Almost all the language versions have a TextTestFixture, but not all of them are configured to actually be runnable with texttest. For that you need an entry in the file texttests/config.gr specifying how to execute the TextTestFixture. 

Plus, the C# version has a test included that uses Approvals. I haven't done the same for the other translations, at the time when that one was contributed, there wasn't an Approvals library for other languages. So it's a bit of an anomaly.

 I do think it's a useful part of the exercise to try writing your own tests first before looking at the provided tests. I would prefer the texttests and the Approvals tests were in a 'with_tests' branch. I haven't had the energy to do this change, as you point out, it's a lot of work. 

At present I think I am content with the status quo. However, your help with an entry for php in the 'config.gr' could be useful, if you want to try out texttest yourself?

**Comment by Pen-y-Fan** [comment]
PHP updated with ApprovalTest and accepted.
Closing the question.
Thanks 👍
