### ISSUE TITLE
Aged Brie getting 2 points per time step ?

### ISSUE THREAD

**Issue by yanntm** [emilybache/GildedRose-Refactoring-Kata#195]
Hi,

I'm wondering if this is normal or not, the code provided does +=2 on the quality of "aged brie" at each step, which the requirements don't seem to express. 

It's not obvious in the source code, but after refactoring in my solution (without touching semantics) it was glaringly obvious.

There are two updates to quality : 
 * https://github.com/emilybache/GildedRose-Refactoring-Kata/blob/master/csharp/GildedRose.cs#L31
 * https://github.com/emilybache/GildedRose-Refactoring-Kata/blob/master/csharp/GildedRose.cs#L82

I thought the kata was about the new feature, but that existing code was supposedly semantically correct.

thanks for the work on these kata.

**Comment by emilybache** [comment]
Well spotted! Yes the code does some things that aren't fully documented. It's supposed to be legacy code after all 👍  You can basically assume that anything the code does is correct. It's in production, the Gilded Rose Inn is using it. If there is a conflict with the requirements, trust the code in preference.

Happy you had a go at the exercise!

Emily

**Comment by yanntm** [comment]
Ok thanks ! I'm kind of into formal verification, so I tend to trust the specifications too much, I mean Brie does get a *lot* smellier each day in the fridge, and I live in France :) So, it fits.

**Comment by mikalziane** [comment]
Good to know about this hidden "feature" Emily. Is it possible that someone updates the requirements then?

**Comment by emilybache** [comment]
No, the requirements are perfect for the excercise exactly as they are.

**Comment by mikalziane** [comment]
I have problems understanding the exercise. 
You say "f there is a conflict with the requirements, trust the code in preference." 
and " the requirements are perfect for the exercise exactly as they are." 
Obviously they are not "perfect" if code supersedes them so I have to understand what "perfect for the exercise" means
 unless the point is for the requirements to be misleading on purpose. Is this the case? If they are not why keep inconsistency between code and the requirements?

**Comment by emilybache** [comment]
Yes, this is an exercise that is supposed to be like real life. The requirements and code and any inconsistency between them is deliberate and part of the exercise.

**Comment by mikalziane** [comment]
OK then, thank you for the clarification. I'll take the "requirements" as a mere comment on the code then as they are supposed to be in real life ;-)

**Comment by soryy708** [comment]
It was a surprising discovery, but I see how it makes sense from the requirements as written.

> "Aged Brie" actually increases in Quality the older it gets
> Once the sell by date has passed, Quality degrades twice as fast

These two specifications together mean Aged Brie gets 2 points once the sell by date has passed.

But hey, spoilers!
