### ISSUE TITLE
cpp cpptexttest shows unidiomatic C++

### ISSUE THREAD

**Issue by PeterSommerlad** [emilybache/GildedRose-Refactoring-Kata#263]
I would think, that the text output could make use of iostreams or fmt instead of using C's printf. but may be that is part of the refactoring exercise?

**Comment by emilybache** [comment]
It's not intended as part of the refactoring, actually. The texttest fixture is not really meant to be edited, it should just work. At least that's the idea. Use of printf is just my lack of skill with C++ :-) I'd welcome a pull request to fix it.

**Comment by AlganOngun** [comment]
I opened a pull request to fix this issue and add Turkish translation #330
