### ISSUE TITLE
Java version seems to update tickets incorrectly

### ISSUE THREAD

**Issue by Max-Derner** [emilybache/GildedRose-Refactoring-Kata#312]
While testing my own code against the original I believe I've noticed an incorrect edge case.
When tickets have sellIn==10, it is supposed to increase quality by 2 but it does not, it works from 9 and below just fine, same for 5 and below.

**Comment by Max-Derner** [comment]
I'm not totally convinced and I don't want to cause a fuss over nothing, I'm finding it unclear what is being updated and when.

**Comment by codecop** [comment]
Did you see that on the original or refactored code?

**Comment by Max-Derner** [comment]
I thought I noticed it in the original code but I was just being foolish. I hadn't grasped that within the update method, quality needed changing before sellIn was changed. My apologies.
