### ISSUE TITLE
Link to article broken

### ISSUE THREAD

**Issue by ghost** [emilybache/GildedRose-Refactoring-Kata#32]
First of all: excellent idea! Although this kata has become a classic among the software-craftsmanship circles by now, I wanted to congratulate you on the idea and the initiative nevertheless. Probably we will be doing this kata at our company soon.

What I wanted to point out is that the link to the article "[Why Most Solutions to Gilded Rose Miss The Bigger Picture](http://iamnotmyself.com/2012/12/07/why-most-solutions-to-gilded-rose-miss-the-bigger-picture/)", mentioned in the README, seems to be broken (the article does not seem to be available anymore).

I could only access it by consulting Google's cache: 

http://webcache.googleusercontent.com/search?q=cache:ot2ak8m5LUkJ:iamnotmyself.com/2012/12/07/why-most-solutions-to-gilded-rose-miss-the-bigger-picture/+&cd=1&hl=en&ct=clnk&gl=at

If the article is "gone forever", maybe you could compensate it by mentioning the message of the article: that getting a piece of legacy code **in a language _different_ than the one you are familiar with** is part of the challenge (of dealing with legacy systems) itself.

**Comment by usr42** [comment]
Seems to be fixed. So the issue can be closed.
