### ISSUE TITLE
Error on stdout.gr for conjured items expected quality

### ISSUE THREAD

**Issue by jebravos** [emilybache/GildedRose-Refactoring-Kata#359]
I believe there is an error on the file **stdout.gr** for the texttests for the expected values on conjured items (the new feature):

-------- day 0 --------
Conjured Mana Cake, 3, 6
-------- day 1 --------
Conjured Mana Cake, 2, 5
-------- day 2 --------
Conjured Mana Cake, 1, 4
-------- day 3 --------
Conjured Mana Cake, 0, 3
-------- day 4 --------
Conjured Mana Cake, -1, 1
-------- day 5 --------
Conjured Mana Cake, -2, 0
-------- day ... --------

The requirement is  **"Conjured" items degrade in Quality twice as fast as normal items**, so while a normal item quality degrades by 1 each day, the conjured items should degrade by 2 and while normal items quality degrades by 2 once the sell by date has passed, the conjured items should degrade by 4. 

Given that, a test suit for conjured items could be:

-------- day 0 --------
Conjured Mana Cake, 3, 10
-------- day 1 --------
Conjured Mana Cake, 2, 8
-------- day 2 --------
Conjured Mana Cake, 1, 6
-------- day 3 --------
Conjured Mana Cake, 0, 4
-------- day 4 --------
Conjured Mana Cake, -1, 0
-------- day 5 --------
Conjured Mana Cake, -2, 0
-------- day ... --------

**Comment by emilybache** [comment]
This is by design! This test is not intended as a specification, it's a regression test. It will tell you when you change something. You should update it when you implement the feature.
