### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by joejag** [emilybache/GildedRose-Refactoring-Kata#360]
https://github.com/emilybache/GildedRose-Refactoring-Kata/blob/bdcea6016916b4e8ac9c112c08a8d5e2bcb44d5f/ruby/gilded_rose.rb#L7

**Comment by emilybache** [comment]
I don't follow you, what is it you want fixed?

**Comment by joejag** [comment]
Apologies @emilybache, You can ignore this.

I've made a copy of this repo using the "Use this template" feature then accidentally worked on this copy rather than our own.

We are planning on running a CodeSmells workshop tonight online and were looking for a good way to have teams identify the issues. GitHub Issues didn't work too well, so we are going to suggest they use the in-built Github editor by pressing '.' and adding comments directly there.
