### ISSUE TITLE
texttest conjured items

### ISSUE THREAD

**Issue by Facundosalvarez** [emilybache/GildedRose-Refactoring-Kata#408]
The instructions state that conjured items degrade twice as fast as normal items, but the texttest stdout.gr indicates that they degrade at the normal item rate. Therefore, I believe there may be an issue with the conjured items.

**Comment by emilybache** [comment]
I think you misread the requirements - the conjured feature is not yet implemented. It says "This requires an update to our system:" just before it explains how conjured items are supposed to work.

**Comment by samjowen** [comment]
I think the wording could be improved as a user may interpret that they themselves are providing said update to the system. I sure did!
