### ISSUE TITLE
csharpcore Acceptance Tests stay blue (not executed)

### ISSUE THREAD

**Issue by Tyrben** [emilybache/GildedRose-Refactoring-Kata#465]
Hi, 

I am maybe super new in C#, and NUnit and Acceptance Testing... so, pardon my newbeness.
After running the .sln csharpcore project, I don't obtain the .txt of the approval tests.
And my approval tests stays blue (meaning not executed).
But the unit tests pass.

Is the project badly configured, or is there a pre-requisit I miss?

**Comment by emilybache** [comment]
Sounds like your tests are not being executed. I'd check the version of the C# compiler you're using. In my IDE that means right clicking on the solution and checking which .Net SDK it's using. Then I right click on each project and under "properties" I can see the target framework. Make sure it includes a version you have installed, the same one as the overall solution.

**Comment by emilybache** [comment]
I just updated the project now so it should look for version 7. Hopefully that will help.

**Comment by Tyrben** [comment]
hi, thank you for your quick action.

Unfortunately it didn't improve the situation. Neither the help I could find on https://stackoverflow.com/questions/23363073/tests-not-running-in-test-explorer 
I will investigate. And reset from scratch. I'll keep you informed.
Status:
- all nugets up to date
- project openned via csharpcore/GildedRore.sln
- test "foo" fixed and pass

**Comment by luc50514** [comment]
Tyrben.
I had the same issue when I cloned the repo.  You need to add the following packages to the project to have it run the tests.  PM > Install-Package NUnit.ConsoleRunner
PM > Install-Package NUnit3TestAdapter

I found the answer here

https://adolfi.dev/blog/nunit-tests-is-not-found-or-do-not-run-in-visual-studio-s-test-explorer/

**Comment by emilybache** [comment]
thanks for that solution! Is that something that I can fix in the files in this repo? Or do we need a README file that explains how to do this?

**Comment by emilybache** [comment]
Any chance you could send me a pull request for this? I don't seem to be able to reproduce the problem so I don't think I can really fix it. 

Also - could it be something to do with the reporter? The approval test fails and should open a diff window with your favourite diff tool. Perhaps that is not working and it's why the test is not running?

**Comment by luc50514** [comment]
I’m so sorry for dropping this.  I have been doing several training
sessions and been super busy.  Thank you for the content.

Rich Hood, US Youth Soccer Coach and Referee, Taylorsville Kentucky,
502.902.5292
