### ISSUE TITLE
[PHP] Item class should not be final

### ISSUE THREAD

**Issue by schlessera** [emilybache/GildedRose-Refactoring-Kata#494]
When refactoring the PHP version from PHP 5 to PHP 7, the `Item` class was made `final`, but no interface was introduced.
https://github.com/emilybache/GildedRose-Refactoring-Kata/blob/d462c366183fb7245333e1aaf11e555fa7705a7c/php/src/Item.php#L7

Given that:
* the `Item` class cannot be extended now
* the `Item` is not an interface
* the `GildedRose` class directly depends on the concrete `Item` class instead of an interface

... this all makes it technically wrong to use any proper OOP techniques for refactoring this in such a way that items can include any properties about themselves, forcing you to hardcode _all_ behavior into the `GildedRose` or one of its parts in some way. Using `final` without any interfaces in-between generally makes for the type of bad couplig you cannot easily rectify in PHP.

_Note: you can still do these types of operations, as the type is not technically enforced, but this will break static analysis and be conceptually wrong._

I would suggest one of two approaches to allow for better refactoring opportunities in the PHP version:

1. **Remove the `final` keyword from the `Item` class.**
	This would allow something like `LegendaryItem extends Item` to still be accepted in the shop class (which requires items to be of type `Item` as per its docblock).

3. **Turn `Item` into an interface and provide something like a `BaseItem` implementation.** 
	This would allow the shop to type against an interface instead, which opens up refactoring methods like using decorators: `new ConjuredItem( new Item( 'Mana Cake', 1, 4 ) )`.

**Comment by emilybache** [comment]
I think option 1 sounds more true to the original. Can you send me a pull request for this?
