### ISSUE TITLE
Rider doesn't detect unit tests in csharpcore exercise

### ISSUE THREAD

**Issue by danharrisondev** [emilybache/GildedRose-Refactoring-Kata#526]
Rider doesn't detect the NUnit unit tests in the csharpcore project, possibly due to the project setup. Because the unit test project is configured as a console application, I assume that the unit tests aren't being recognized. It's not commonplace to have your unit test project be a console application.

My suggested fix is to have three projects:
* main class library, GildedRose
* unit test project, GildedRoseUnitTests
* approval testing project, GildedRoseApprovalTests

Further instructions for the approval testing also wouldn't go amiss as it's not clear how they should be used.

**Comment by codecop** [comment]
The setup of the different languages is inconsistent. Some put texttestsfixture into main, others into test. Would moving TextTestFixture.cs to gilderose project and making it a console application work?

**Comment by danharrisondev** [comment]
Yes I think that might work!

**Comment by codecop** [comment]
I would be happy to receive a PR from you

**Comment by danharrisondev** [comment]
Cool, I'll look over it this weekend. Thanks codecop!

**Comment by danharrisondev** [comment]
My bad. I was running Rider 2023.2.3 which doesn't support NUnit 4. I upgraded and everything works out of the box. No PR needed! 😊

For anyone else having this issue, update your Rider!
