### ISSUE TITLE
Why are there 3 c# projects?

### ISSUE THREAD

**Issue by StefH** [emilybache/GildedRose-Refactoring-Kata#541]
I see these 3 C# projects?

- [csharp](https://github.com/emilybache/GildedRose-Refactoring-Kata/tree/main/csharp)
- [csharpcore-Verify.xunit](https://github.com/emilybache/GildedRose-Refactoring-Kata/tree/main/csharpcore-Verify.xunit)
- [csharpcore](https://github.com/emilybache/GildedRose-Refactoring-Kata/tree/main/csharpcore)

These are all very similar; whould it make sense to just keep the `csharpcore` and rename this to `csharp` ?

**Comment by codecop** [comment]
Yes csharp and csharpcore look similar, both using unit - could be merged/unified. The xunit one is set up using xunit and should stay like that. Other languages have different folders for different testing frameworks.

**Comment by StefH** [comment]
OK. I see.

Maybe a good idea to merge the `csharpcore` and `csharp` and rename that new project to `csharpcore-Verify.NUnit`

Or also remove the `Verify` from both so that we end up with:
- `csharpcore-NUnit`
- `csharpcore-xUnit`

I can make a PR.

**Comment by codecop** [comment]
Yes good idea to drop the verify word. Yes looking forward to your PR

**Comment by codecop** [comment]
Solved by #542
