### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by rjekker** [emilybache/GildedRose-Refactoring-Kata#579]
The link to the article [Why Most Solutions .. Miss the Bigger Picture](https://iamnotmyself.com/why-most-solutions-to-gilded-rose-miss-the-bigger-picture/) in the readme seems to be broken. 

I found the same (I guess?) article at a different url: https://www.codurance.com/katas/gilded-rose, maybe you can use that URL instead.

**Comment by emilybache** [comment]
Unfortunately that's not the same article. I suspect Bobby Johnson's blog is no longer on the internet. Thanks for pointing out the problem. I found it on wayback machine, will update the link.
